// create-rspc-app/templates/react_base_axum/src/main.tsx
import React from "react";
import ReactDOM from "react-dom/client";
import App from "./App";
import rspc, { client, queryClient } from "./query.axum";

ReactDOM.createRoot(document.getElementById("root") as HTMLElement).render(
  <React.StrictMode>
    <rspc.Provider client={client} queryClient={queryClient}>
      <App />
    </rspc.Provider>
  </React.StrictMode>
);

// crates/create-rspc-app/templates/solid_base_axum/src/index.tsx
/* @refresh reload */
import { render } from "solid-js/web";
import rspc, { client, queryClient } from "./query.axum";
import App from "./App";

render(
  () => (
    <rspc.Provider client={client} queryClient={queryClient}>
      <App />
    </rspc.Provider>
  ),
  document.getElementById("root") as HTMLElement
);
