// packages/react-query/src/index.tsx
"use client";

import * as tanstack from "@tanstack/react-query";
import * as rspc from "@rspc/query-core";
import React from "react";

export function createReactQueryHooks<P extends rspc.ProceduresDef>() {
  const Context = React.createContext<rspc.Context<P>>(undefined!);

  const helpers = rspc.createQueryHookHelpers({
    useContext: () => React.useContext(Context),
  });

  type UseQueryOptions<K extends rspc.inferQueries<P>["key"] & string> =
    rspc.HookOptions<
      P,
      rspc.QueryOptionsOmit<
        tanstack.UseQueryOptions<
          rspc.inferQueryResult<P, K>,
          rspc.inferQueryError<P, K>,
          rspc.inferQueryResult<P, K>,
          [K, rspc.inferQueryInput<P, K>]
        >
      >
    >;

  function useQuery<K extends rspc.inferQueries<P>["key"] & string>(
    keyAndInput: [
      key: K,
      ...input: rspc._inferProcedureHandlerInput<P, "queries", K>
    ],
    opts?: UseQueryOptions<K>
  ) {
    return tanstack.useQuery<
      rspc.inferQueryResult<P, K>,
      rspc.inferQueryError<P, K>,
      rspc.inferQueryResult<P, K>,
      [K, rspc.inferQueryInput<P, K>]
    >(helpers.useQueryArgs(keyAndInput, opts));
  }

  type UseMutationOptions<
    K extends rspc.inferMutations<P>["key"] & string,
    TContext = unknown
  > = rspc.HookOptions<
    P,
    tanstack.UseMutationOptions<
      rspc.inferMutationResult<P, K>,
      rspc.inferMutationError<P, K>,
      rspc.inferMutationInput<P, K> extends never
        ? undefined
        : rspc.inferMutationInput<P, K>,
      TContext
    >
  >;

  function useMutation<
    K extends rspc.inferMutations<P>["key"] & string,
    TContext = unknown
  >(key: K | [K], opts?: UseMutationOptions<K, TContext>) {
    return tanstack.useMutation<
      rspc.inferMutationResult<P, K>,
      rspc.inferMutationError<P, K>,
      rspc.inferMutationInput<P, K> extends never
        ? undefined
        : rspc.inferMutationInput<P, K>,
      TContext
    >(helpers.useMutationArgs(key, opts));
  }

  function useSubscription<
    K extends rspc.inferSubscriptions<P>["key"] & string
  >(
    keyAndInput: [
      key: K,
      ...input: rspc._inferProcedureHandlerInput<P, "subscriptions", K>
    ],
    opts: rspc.HookOptions<
      P,
      rspc.SubscriptionOptions<rspc.inferSubscription<P, K>>
    >
  ) {
    const [client, rawOpts] = helpers.useExtractOps(opts);

    return React.useEffect(
      () =>
        helpers.handleSubscription({
          client,
          keyAndInput,
          opts: rawOpts,
        }),
      [tanstack.hashKey(keyAndInput), opts.enabled ?? true]
    );
  }

  // function useInfiniteQuery<K extends inferInfiniteQueries<P>["key"] & string>(
  //   keyAndInput: [
  //     key: K,
  //     ...input: _inferInfiniteQueryProcedureHandlerInput<P, K>
  //   ],
  //   opts?: Omit<
  //     UseInfiniteQueryOptions<
  //       inferInfiniteQueryResult<P, K>,
  //       RSPCError,
  //       inferInfiniteQueryResult<P, K>,
  //       inferInfiniteQueryResult<P, K>,
  //       [K, inferQueryInput<P, K>]
  //     >,
  //     "queryKey" | "queryFn"
  //   > &
  //     TBaseOptions
  // ): UseInfiniteQueryResult<inferInfiniteQueryResult<P, K>, RSPCError> {
  //   const { rspc, ...rawOpts } = opts ?? {};
  //   let client = rspc?.client;
  //   if (!client) {
  //     client = useContext().client;
  //   }

  //   return __useInfiniteQuery({
  //     queryKey: mapQueryKey(keyAndInput as any),
  //     queryFn: async () => {
  //       throw new Error("TODO"); // TODO: Finish this
  //     },
  //     ...(rawOpts as any),
  //   });
  // }

  return {
    _rspc_def: undefined! as P, // This allows inferring the operations type from TS helpers
    Provider: ({
      children,
      client,
      queryClient,
    }: React.PropsWithChildren<rspc.Context<P>>) => (
      <Context.Provider
        value={{
          client,
          queryClient,
        }}
      >
        <tanstack.QueryClientProvider client={queryClient}>
          {children}
        </tanstack.QueryClientProvider>
      </Context.Provider>
    ),
    useContext: helpers.useContext,
    useQuery,
    // useInfiniteQuery,
    useMutation,
    useSubscription,
  };
}

// packages/solid-query/src/index.tsx
import * as Solid from "solid-js";
import * as tanstack from "@tanstack/solid-query";
import * as rspc from "@rspc/query-core";

export function createSolidQueryHooks<P extends rspc.ProceduresDef>() {
  const Context = Solid.createContext<rspc.Context<P> | null>(null);

  const helpers = rspc.createQueryHookHelpers({
    useContext: () => Solid.useContext(Context),
  });

  type CreateQueryOptions<K extends rspc.inferQueries<P>["key"] & string> =
    rspc.HookOptions<
      P,
      rspc.QueryOptionsOmit<
        tanstack.SolidQueryOptions<
          rspc.inferQueryResult<P, K>,
          rspc.inferQueryError<P, K>,
          rspc.inferQueryResult<P, K>,
          [K, rspc.inferQueryInput<P, K>]
        >
      >
    >;

  function createQuery<K extends rspc.inferQueries<P>["key"] & string>(
    keyAndInput: () => [
      key: K,
      ...input: rspc._inferProcedureHandlerInput<P, "queries", K>
    ],
    opts?: CreateQueryOptions<K>
  ) {
    return tanstack.createQuery(() => helpers.useQueryArgs(keyAndInput, opts));
  }

  type CreateMutationOptions<
    K extends rspc.inferMutations<P>["key"] & string,
    TContext
  > = rspc.HookOptions<
    P,
    tanstack.CreateMutationOptions<
      rspc.inferMutationResult<P, K>,
      rspc.inferMutationError<P, K>,
      rspc.inferMutationInput<P, K> extends never
        ? undefined
        : rspc.inferMutationInput<P, K>,
      TContext
    >
  >;

  function createMutation<
    K extends rspc.inferMutations<P>["key"] & string,
    TContext = unknown
  >(key: K | [K], opts?: CreateMutationOptions<K, TContext>) {
    return tanstack.createMutation(() => helpers.useMutationArgs(key, opts));
  }

  function createSubscription<
    K extends rspc.inferSubscriptions<P>["key"] & string
  >(
    keyAndInput: () => [
      key: K,
      ...input: rspc._inferProcedureHandlerInput<P, "subscriptions", K>
    ],
    opts: () => rspc.HookOptions<
      P,
      rspc.SubscriptionOptions<rspc.inferSubscription<P, K>>
    >
  ) {
    return Solid.createEffect(
      Solid.on(
        () => [keyAndInput(), opts?.()] as const,
        ([keyAndInput, opts]) => {
          const [client, rawOpts] = helpers.useExtractOps(opts ?? {});

          // TODO: solid-start useRequest

          const cleanup = helpers.handleSubscription({
            client,
            keyAndInput,
            opts: rawOpts,
          });

          Solid.onCleanup(() => cleanup?.());
        }
      )
    );
  }

  // function createInfiniteQuery<
  //   K extends rspc.inferInfiniteQueries<P>["key"] & string
  // >(
  //   keyAndInput: () => [
  //     key: K,
  //     ...input: Omit<
  //       rspc._inferInfiniteQueryProcedureHandlerInput<P, K>,
  //       "cursor"
  //     >
  //   ],
  //   opts?: Omit<
  //     tanstack.CreateInfiniteQueryOptions<
  //       rspc.inferInfiniteQueryResult<P, K>,
  //       rspc.inferInfiniteQueryError<P, K>,
  //       rspc.inferInfiniteQueryResult<P, K>,
  //       rspc.inferInfiniteQueryResult<P, K>,
  //       () => [K, Omit<rspc.inferQueryInput<P, K>, "cursor">]
  //     >,
  //     "queryKey" | "queryFn"
  //   > &
  //     TBaseOptions
  // ) {
  //   const { rspc, ...rawOpts } = opts ?? {};
  //   let client = rspc?.client;
  //   if (!client) {
  //     client = useContext().client;
  //   }

  //   return tanstack.createInfiniteQuery({
  //     queryKey: keyAndInput,
  //     queryFn: () => {
  //       throw new Error("TODO"); // TODO: Finish this
  //     },
  //     ...(rawOpts as any),
  //   });
  // }

  return {
    _rspc_def: undefined! as P, // This allows inferring the operations type from TS helpers
    Provider: (props: Solid.ParentProps<rspc.Context<P>>) => (
      <Context.Provider
        value={{
          client: props.client,
          queryClient: props.queryClient,
        }}
      >
        <tanstack.QueryClientProvider client={props.queryClient}>
          {props.children}
        </tanstack.QueryClientProvider>
      </Context.Provider>
    ),
    useContext: helpers.useContext,
    createQuery,
    // createInfiniteQuery,
    createMutation,
    createSubscription,
  };
}
