// examples/web/src/components/solid/Provider.tsx
/** @jsxImportSource solid-js */

import { QueryClientProvider } from "@tanstack/solid-query";
import { ParentProps } from "solid-js";

import { client, queryClient, rspc } from ".";

export function Provider(props: ParentProps) {
	return (
		<rspc.Provider client={client} queryClient={queryClient}>
			<QueryClientProvider client={queryClient}>
				{props.children}
			</QueryClientProvider>
		</rspc.Provider>
	);
}

// examples/web/src/components/react/Provider.tsx
import { QueryClientProvider } from "@tanstack/react-query";
import type { PropsWithChildren } from "react";

import { client, queryClient, rspc } from ".";

export function Provider({ children }: PropsWithChildren) {
	return (
		<rspc.Provider client={client} queryClient={queryClient}>
			<QueryClientProvider client={queryClient}>{children}</QueryClientProvider>
		</rspc.Provider>
	);
}
